services:
    mongo:
        image: mongo:latest
        volumes:
            - mongo_data:/data/db
        ports:
            - "27017:27017"
        env_file:
            - .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}

volumes:
    mongo_data:
